# Generated by Django 3.2.16 on 2025-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_auto_20250425_2258"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
